export * from './custom-code-region-markers.variables';
export * from './custom-code-region-regex.variables';
export * from './diff-editor-model.interface';
export * from './file-type.enum';
export * from './markers.variables';
export * from './mock.code';
export * from './monaco-editor-model.interface';
export * from './monaco-editor-region.interface';
export * from './monaco-editor-default.config';