import { ButtonRedirectTarget } from './button-redirect-target.enum';
import { ButtonColorType } from './button-color-type.enum';
import { ButtonIconPlacement } from './button-icon-placement.enum';
import { ButtonShape } from './button-shape.type';
import { ButtonSize } from './button-size.type';
import { ButtonType } from './button-type.type';
import { FormButtonType } from './form-button-type.enum';
import { TooltipPlacement } from './tooltip-placement.enum';
import { ButtonActionBehavior } from './button-action-behavior.enum';
import { ButtonRedirectMode } from './button-redirect-mode.enum';
import { BoxShadowConfig, ColorConfig, SizeConfig, SpacingConfig, BorderConfig } from '@rapider/angular-components/core/style';
import { IconComponentConfig } from '@rapider/angular-components/core/icon';

export interface ButtonComponentConfig {
  key?: string;
  text?: string;
  type?: ButtonType;
  shape?: ButtonShape;
  size?: ButtonSize;
  transparent?: boolean;
  loading?: boolean;
  block?: boolean;
  disabled?: boolean;
  icon?: IconComponentConfig;
  colorType?: ButtonColorType;
  popconfirmTitle?: string;
  emitWithoutPopconfirm?: boolean;
  iconPlacement?: ButtonIconPlacement;
  formButtonType?: FormButtonType;
  borderSettings?: BorderConfig;
  marginSettings?: SpacingConfig;
  paddingSettings?: SpacingConfig;
  shadowSettings?: BoxShadowConfig;
  customColorSettings?: ColorConfig;
  customSizeSettings?: SizeConfig;
  tooltipText?: string;
  popconfirmCancelText?: string;
  popconfirmOkText?: string;
  popconfirmOkDanger?: boolean;
  behavior?: ButtonActionBehavior;
  redirectUrl?: string;
  redirectMode?: ButtonRedirectMode;
  redirectTarget?: ButtonRedirectTarget;
  tooltipPlacement?: TooltipPlacement;
  customCssClass?: string;
}
